Repository UniAuth/uniauth.github.io, pull requests merged in 2021-02, with the labels that each got.

#8 added footer github logo to direct the user to the organisation repo
  index.html
Labels: user=lopeselio:score=10

#10 feat(ui): add video section
  index.html
Labels: user=kdsinghcoder:score=50

#14 fix(navbar): navbar-logo visible after scroll
  index.html
Labels: user=Abhijay007:score=25

#15 fix(animation): add privacy card flip
  index.html
Labels: user=Abhijay007:score=25

#19 fix(ui): excess margin on left side
  index.html
Labels: user=m-code12:score=25

#18 feat(footer): add twitter handle
  index.html
Labels: user=Abhijay007:score=10

#22 feat(footer): add micro-animations
  assets/css/icons.css
  index.html
Labels: user=Abhijay007:score=50

#23 feat(twitter): add feed
  index.html
Labels: user=Abhijay007:score=50

#24 fix(viewport): improved responsiveness, fixes #6
  index.html
Labels: user=Abhijay007:score=25

#27 Added email and discord icon
  assets/css/icons.css
  index.html
Labels: user=MASTERCHIEF011:score=25
